#############################################################################
# Makefile for building: curso-qt-osl-tareas-exe
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  curso-qt-osl-tareas/curso-qt-osl-tareas.pro
# Template: app
# Command: /home/elias/programas/Qt5/5.2.1/gcc_64/bin/qmake -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile curso-qt-osl-tareas/curso-qt-osl-tareas.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../programas/Qt5/5.2.1/gcc_64/mkspecs/linux-clang -Icurso-qt-osl-tareas -I../../../programas/Qt5/5.2.1/gcc_64/include -I../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets -I../../../programas/Qt5/5.2.1/gcc_64/include/QtSql -I../../../programas/Qt5/5.2.1/gcc_64/include/QtGui -I../../../programas/Qt5/5.2.1/gcc_64/include/QtCore -I. -I. -I.
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/home/elias/programas/Qt5/5.2.1/gcc_64 -Wl,-rpath,/home/elias/programas/Qt5/5.2.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/elias/programas/Qt5/5.2.1/gcc_64/lib -lQt5Widgets -lQt5Sql -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/elias/programas/Qt5/5.2.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = curso-qt-osl-tareas/main.cpp \
		curso-qt-osl-tareas/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/clang.conf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/resources.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/moc.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/uic.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/lex.prf \
		curso-qt-osl-tareas/curso-qt-osl-tareas/curso-qt-osl-tareas.pro \
		curso-qt-osl-tareas/curso-qt-osl-tareas.pro
QMAKE_TARGET  = curso-qt-osl-tareas-exe
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = curso-qt-osl-tareas-exe


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: curso-qt-osl-tareas/curso-qt-osl-tareas.pro ../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/clang.conf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/linux-clang/qmake.conf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/resources.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/moc.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/uic.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/lex.prf \
		curso-qt-osl-tareas/curso-qt-osl-tareas.pro \
		/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Widgets.prl \
		/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Gui.prl \
		/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Core.prl \
		/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Sql.prl
	$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile curso-qt-osl-tareas/curso-qt-osl-tareas.pro
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/unix.conf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/linux.conf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/common/clang.conf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/qconfig.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/linux-clang/qmake.conf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/default_post.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qml_debug.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/qt.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/resources.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/moc.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/uic.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/unix/thread.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/yacc.prf:
../../../programas/Qt5/5.2.1/gcc_64/mkspecs/features/lex.prf:
curso-qt-osl-tareas/curso-qt-osl-tareas.pro:
/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Widgets.prl:
/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Gui.prl:
/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Core.prl:
/home/elias/programas/Qt5/5.2.1/gcc_64/lib/libQt5Sql.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile curso-qt-osl-tareas/curso-qt-osl-tareas.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/curso-qt-osl-tareas-exe1.0.0 || mkdir -p .tmp/curso-qt-osl-tareas-exe1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/curso-qt-osl-tareas-exe1.0.0/ && $(COPY_FILE) --parents curso-qt-osl-tareas/dbconnection.h curso-qt-osl-tareas/mainwindow.h .tmp/curso-qt-osl-tareas-exe1.0.0/ && $(COPY_FILE) --parents curso-qt-osl-tareas/main.cpp curso-qt-osl-tareas/mainwindow.cpp .tmp/curso-qt-osl-tareas-exe1.0.0/ && $(COPY_FILE) --parents curso-qt-osl-tareas/mainwindow.ui .tmp/curso-qt-osl-tareas-exe1.0.0/ && (cd `dirname .tmp/curso-qt-osl-tareas-exe1.0.0` && $(TAR) curso-qt-osl-tareas-exe1.0.0.tar curso-qt-osl-tareas-exe1.0.0 && $(COMPRESS) curso-qt-osl-tareas-exe1.0.0.tar) && $(MOVE) `dirname .tmp/curso-qt-osl-tareas-exe1.0.0`/curso-qt-osl-tareas-exe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/curso-qt-osl-tareas-exe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qglobal.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qconfig.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmutex.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlogging.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qflags.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobject.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstring.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qchar.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlist.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qiterator.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qisenum.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmargins.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qrect.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsize.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qpoint.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpalette.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qcolor.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qrgb.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qpair.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qregexp.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qbrush.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvector.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qregion.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qline.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qtransform.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qimage.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qhash.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfont.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qcursor.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qevent.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvariant.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdebug.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlocale.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qset.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qurl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfile.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qicon.h \
		curso-qt-osl-tareas/dbconnection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlDatabase \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqldatabase.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsql.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlQuery \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlquery.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlError \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlerror.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlRecord \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlrecord.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlField \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlfield.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/QDateTime \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdatetime.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QMessageBox \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/QDesktopServices \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qdesktopservices.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstandardpaths.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/QDir \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdir.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfileinfo.h \
		curso-qt-osl-tareas/mainwindow.h
	/home/elias/programas/Qt5/5.2.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) curso-qt-osl-tareas/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: curso-qt-osl-tareas/mainwindow.ui
	/home/elias/programas/Qt5/5.2.1/gcc_64/bin/uic curso-qt-osl-tareas/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: curso-qt-osl-tareas/main.cpp curso-qt-osl-tareas/mainwindow.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qglobal.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qconfig.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmutex.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlogging.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qflags.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobject.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstring.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qchar.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlist.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qiterator.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qisenum.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmargins.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qrect.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsize.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qpoint.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpalette.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qcolor.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qrgb.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qpair.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qregexp.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qbrush.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvector.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qregion.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qline.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qtransform.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qimage.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qhash.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfont.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qcursor.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qevent.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvariant.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdebug.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlocale.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qset.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qurl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfile.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qicon.h \
		curso-qt-osl-tareas/dbconnection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlDatabase \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqldatabase.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsql.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlQuery \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlquery.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlError \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlerror.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlRecord \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlrecord.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlField \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlfield.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/QDateTime \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdatetime.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QMessageBox \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/QDesktopServices \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qdesktopservices.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstandardpaths.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/QDir \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdir.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfileinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QApplication \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qapplication.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qeventloop.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qguiapplication.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o curso-qt-osl-tareas/main.cpp

mainwindow.o: curso-qt-osl-tareas/mainwindow.cpp curso-qt-osl-tareas/mainwindow.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qglobal.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qconfig.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmutex.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlogging.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qflags.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobject.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstring.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qchar.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlist.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qiterator.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qisenum.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmargins.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qrect.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsize.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qpoint.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpalette.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qcolor.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qrgb.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qpair.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qregexp.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qbrush.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvector.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qregion.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qline.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qtransform.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qimage.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qhash.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfont.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qcursor.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qevent.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qvariant.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qmap.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdebug.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qlocale.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qset.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qurl.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfile.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qicon.h \
		curso-qt-osl-tareas/dbconnection.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlDatabase \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqldatabase.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsql.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlQuery \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlquery.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlError \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlerror.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlRecord \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlrecord.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/QSqlField \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtSql/qsqlfield.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/QDateTime \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdatetime.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QMessageBox \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/QDesktopServices \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qdesktopservices.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qstandardpaths.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/QDir \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qdir.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qfileinfo.h \
		ui_mainwindow.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/QVariant \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QAction \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qaction.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QApplication \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qapplication.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qeventloop.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qguiapplication.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qinputmethod.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QButtonGroup \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QHeaderView \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qheaderview.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qframe.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qstyleoption.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtGui/qvalidator.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtCore/qregularexpression.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qslider.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qabstractslider.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qstyle.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qtabbar.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qrubberband.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QMenuBar \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmenubar.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qmenu.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QStatusBar \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/qstatusbar.h \
		../../../programas/Qt5/5.2.1/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o curso-qt-osl-tareas/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

